from flask import Flask
from database import db
from models.item_master import ItemMaster
from models.recipe_master import RecipeMaster

def insert_recipe_master_data():
    """
    Inserts recipe details into the RecipeMaster table.
    Assumes ItemMaster table is already populated with both raw materials and finished goods.
    """
    try:
        recipe_details = [
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Pork 80CL", "kg_per_batch": 40.00, "percentage": 37.40},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 20.00, "percentage": 18.70},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Ice", "kg_per_batch": 25.00, "percentage": 23.38},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 15.00, "percentage": 14.03},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Salt", "kg_per_batch": 1.30, "percentage": 1.22},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Vienna Gold", "kg_per_batch": 0.60, "percentage": 0.56},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "STPP", "kg_per_batch": 0.30, "percentage": 0.28},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Fresh Red", "kg_per_batch": 0.10, "percentage": 0.09},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "ISP", "kg_per_batch": 0.50, "percentage": 0.47},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Potato Starch", "kg_per_batch": 1.00, "percentage": 0.94},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Colorado CM", "kg_per_batch": 0.06, "percentage": 0.06},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.04, "percentage": 0.03},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Frischex", "kg_per_batch": 0.50, "percentage": 0.47},
            {"recipe_code": "2006", "description": "Frankfurter - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.40, "percentage": 2.24},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Veal Trim", "kg_per_batch": 20.000, "percentage": 18.44},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Chicken Skin", "kg_per_batch": 25.000, "percentage": 23.05},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Ice", "kg_per_batch": 25.000, "percentage": 23.05},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Chicken Trimming", "kg_per_batch": 30.000, "percentage": 27.67},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Salt", "kg_per_batch": 1.500, "percentage": 1.38},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.150, "percentage": 0.14},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Fresh Red", "kg_per_batch": 0.100, "percentage": 0.09},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Vienna Gold", "kg_per_batch": 0.600, "percentage": 0.55},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.28},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Potato Starch", "kg_per_batch": 2.000, "percentage": 1.84},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "ISP", "kg_per_batch": 0.80, "percentage": 0.74},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Colorado CM", "kg_per_batch": 0.04, "percentage": 0.04},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.05, "percentage": 0.05},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Frischex", "kg_per_batch": 0.50, "percentage": 0.46},
            {"recipe_code": "6002", "description": "Veal Frankfurter Mix WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.40, "percentage": 2.21},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 50.00, "percentage": 45.69},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Pork Back Fat", "kg_per_batch": 25.000, "percentage": 22.85},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Ice", "kg_per_batch": 25.000, "percentage": 22.85},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Salt", "kg_per_batch": 1.800, "percentage": 1.64},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Zitromat (Raps)", "kg_per_batch": 0.200, "percentage": 0.18},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "dried parsely", "kg_per_batch": 0.50, "percentage": 0.46},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.20, "percentage": 0.18},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Weisswurst Spice", "kg_per_batch": 0.700, "percentage": 0.64},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Onion Powder", "kg_per_batch": 0.150, "percentage": 0.14},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "ISP", "kg_per_batch": 2.000, "percentage": 1.83},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Preservative", "kg_per_batch": 0.080, "percentage": 0.07},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.500, "percentage": 0.46},
            {"recipe_code": "2005", "description": "Weisswurst - WIP", "raw_material": "Potato Starch", "kg_per_batch": 3.000, "percentage": 2.74},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 45.000, "percentage": 42.01},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 25, "percentage": 23.34},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Ice", "kg_per_batch": 20, "percentage": 18.67},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 10, "percentage": 9.33},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Salt", "kg_per_batch": 1.8, "percentage": 1.68},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.5, "percentage": 0.47},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.4, "percentage": 0.37},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Nutmeg Ground", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Caraway Ground", "kg_per_batch": 0.4, "percentage": 0.37},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Zitromat (Raps)", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Majoram", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Preservative", "kg_per_batch": 0.08, "percentage": 0.07},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "ISP", "kg_per_batch": 1, "percentage": 0.93},
            {"recipe_code": "2002", "description": "Thuringer Bratwurst - WIP", "raw_material": "Potato Starch", "kg_per_batch": 2, "percentage": 1.87},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Pork Top Site SSF", "kg_per_batch": 50, "percentage": 50.12},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Water", "kg_per_batch": 13, "percentage": 13.03},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Red Kidney Beans", "kg_per_batch": 19, "percentage": 19.05},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Minced Chilli", "kg_per_batch": 3, "percentage": 3.01},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Salt", "kg_per_batch": 0.63, "percentage": 0.63},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Pepper black Ground", "kg_per_batch": 0.23, "percentage": 0.23},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Onion Fresh diced", "kg_per_batch": 2, "percentage": 2.00},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.3, "percentage": 0.30},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Tomato Paste", "kg_per_batch": 9, "percentage": 9.02},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Novation 2600", "kg_per_batch": 2, "percentage": 2.00},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Emulsan KW1000", "kg_per_batch": 0.5, "percentage": 0.50},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Fermex (GM)", "kg_per_batch": 0.0333, "percentage": 0.03},
            {"recipe_code": "20001", "description": "Chilli Con Carne WIP", "raw_material": "Paprika Liquid 100.000", "kg_per_batch": 0.06, "percentage": 0.06},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 40, "percentage": 37.38},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Chicken MDM", "kg_per_batch": 15, "percentage": 14.02},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Ice", "kg_per_batch": 15, "percentage": 14.02},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Pork Jowls", "kg_per_batch": 30, "percentage": 28.04},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Salt", "kg_per_batch": 1.5, "percentage": 1.40},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Fresh Red", "kg_per_batch": 0.08, "percentage": 0.07},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Debreziner Spice (RAPS)", "kg_per_batch": 1.8, "percentage": 1.68},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "STPP", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.07, "percentage": 0.07},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Chilli Ground", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Fermex (GM)", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Frischex", "kg_per_batch": 0.5, "percentage": 0.47},
            {"recipe_code": "2008", "description": "Debrecziner WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.24},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 40, "percentage": 36.48},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 40, "percentage": 36.48},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Water", "kg_per_batch": 10, "percentage": 9.12},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 10, "percentage": 9.12},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Salt", "kg_per_batch": 1.5, "percentage": 1.37},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.07, "percentage": 0.06},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Chorizo Spice (RAPS)", "kg_per_batch": 1.2, "percentage": 1.09},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "STPP", "kg_per_batch": 0.5, "percentage": 0.46},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.07, "percentage": 0.06},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.06, "percentage": 0.05},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Chilli Ground", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Paprika Liquid 100.000", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Frischex", "kg_per_batch": 0.5, "percentage": 0.46},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.19},
            {"recipe_code": "2015", "description": "Chorizo - WIP", "raw_material": "Potato Starch", "kg_per_batch": 3, "percentage": 2.74},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 50, "percentage": 47.26},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Pork Fat (Shoulder & Leg)", "kg_per_batch": 25, "percentage": 23.63},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Ice", "kg_per_batch": 25, "percentage": 23.63},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Salt", "kg_per_batch": 1.2, "percentage": 1.13},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Meat Loaf Laudatio", "kg_per_batch": 0.6, "percentage": 0.57},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.07, "percentage": 0.07},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.08, "percentage": 0.08},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.5, "percentage": 0.47},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Frischex", "kg_per_batch": 0.5, "percentage": 0.47},
            {"recipe_code": "3012", "description": "Leberkaes - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.27},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "Chicken Trimming", "kg_per_batch": 27, "percentage": 27.00},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 22, "percentage": 22.00},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 25, "percentage": 25.00},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "Water", "kg_per_batch": 16, "percentage": 16.00},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "Onions fresh", "kg_per_batch": 1, "percentage": 1.00},
            {"recipe_code": "2022", "description": "Chicken Blanched Chipolata - WIP", "raw_material": "GF Premix Chicken F25A", "kg_per_batch": 9, "percentage": 9.00},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Pork 75 CL", "kg_per_batch": 40, "percentage": 36.70},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Pork Jowls", "kg_per_batch": 24, "percentage": 22.02},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Chicken MDM", "kg_per_batch": 6, "percentage": 5.51},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Ice", "kg_per_batch": 16, "percentage": 14.68},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Pork Back Fat", "kg_per_batch": 20, "percentage": 18.35},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Salt", "kg_per_batch": 1.7, "percentage": 1.56},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.06, "percentage": 0.06},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Garlic Powder", "kg_per_batch": 0.12, "percentage": 0.11},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Krainer Sausage Spice", "kg_per_batch": 0.6, "percentage": 0.55},
            {"recipe_code": "6004.6", "description": "Spekacky", "raw_material": "Colorado CM", "kg_per_batch": 0.05, "percentage": 0.05},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Beef 75CL", "kg_per_batch": 30, "percentage": 25.43},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 25, "percentage": 21.19},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 20, "percentage": 16.95},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Water", "kg_per_batch": 25, "percentage": 21.19},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Onions fresh", "kg_per_batch": 2, "percentage": 1.70},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Salt", "kg_per_batch": 1.55, "percentage": 1.31},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.13},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Vienna Gold", "kg_per_batch": 0.7, "percentage": 0.59},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "STPP", "kg_per_batch": 0.5, "percentage": 0.42},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.1, "percentage": 0.08},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Potato Starch", "kg_per_batch": 6, "percentage": 5.09},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "ISP", "kg_per_batch": 4, "percentage": 3.39},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.070, "percentage": 0.06},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.500, "percentage": 0.42},
            {"recipe_code": "2020", "description": "Beef Hot Dog - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.400, "percentage": 2.03},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 24.000, "percentage": 22.50},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Spiess Fat", "kg_per_batch": 20.000, "percentage": 18.75},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Ice", "kg_per_batch": 24.000, "percentage": 22.50},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Emulsion Trim", "kg_per_batch": 32.000, "percentage": 30.00},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Salt", "kg_per_batch": 0.600, "percentage": 0.56},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.150, "percentage": 0.14},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.28},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.080, "percentage": 0.07},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 1.700, "percentage": 1.59},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Fermented Rice", "kg_per_batch": 0.050, "percentage": 0.05},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "ISP", "kg_per_batch": 1.000, "percentage": 0.94},
            {"recipe_code": "2033", "description": "Costco Tasty Juicy Hot Dogs NEW ZEALAND - WIP", "raw_material": "Potato Starch", "kg_per_batch": 2.000, "percentage": 1.87},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 45.000, "percentage": 44.64},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 10.000, "percentage": 9.92},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 15.000, "percentage": 14.88},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "Water Iced (below 1⁰C)", "kg_per_batch": 25.000, "percentage": 24.80},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "JMT Frankfurter EZY Mix", "kg_per_batch": 5.000, "percentage": 4.96},
            {"recipe_code": "2034", "description": "Majestic Hotdogs Regular - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.800, "percentage": 0.79},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 30.000, "percentage": 26.93},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Spiess Fat", "kg_per_batch": 13, "percentage": 11.67},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Ice", "kg_per_batch": 25, "percentage": 22.45},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 32, "percentage": 28.73},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Salt", "kg_per_batch": 0.6, "percentage": 0.54},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.150, "percentage": 0.13},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.080, "percentage": 0.07},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.200, "percentage": 0.18},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 1.700, "percentage": 1.53},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Fermented Rice", "kg_per_batch": 0.050, "percentage": 0.04},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "ISP", "kg_per_batch": 2.100, "percentage": 1.89},
            {"recipe_code": "2032", "description": "Costco Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Potato Starch", "kg_per_batch": 3.000, "percentage": 2.69},
            {"recipe_code": "2032", "description": "Costro Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "FUMARO", "kg_per_batch": 0.200, "percentage": 0.18},
            {"recipe_code": "2032", "description": "Costro Tasty Juicy Hot Dogs DOMESTIC - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.15},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Chicken Trimming", "kg_per_batch": 35, "percentage": 32.96},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 25, "percentage": 23.54},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 25, "percentage": 23.54},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Water", "kg_per_batch": 15.000, "percentage": 14.13},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Salt", "kg_per_batch": 1.400, "percentage": 1.32},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.28},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Rice Flour", "kg_per_batch": 2.000, "percentage": 1.88},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "ISP", "kg_per_batch": 1.000, "percentage": 0.94},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Mace Ground", "kg_per_batch": 0.150, "percentage": 0.14},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.300, "percentage": 0.28},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Thyme", "kg_per_batch": 0.200, "percentage": 0.19},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Onion Powder", "kg_per_batch": 0.050, "percentage": 0.05},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.700, "percentage": 0.66},
            {"recipe_code": "2025", "description": "Chicken & Thyme Chipolata - WIP", "raw_material": "Preservative Dry Sodium Sulphite 25kg", "kg_per_batch": 0.080, "percentage": 0.08},
            {"recipe_code": "2205", "description": "CFC Longganisa Sausage - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 50, "percentage": 46.82},
            {"recipe_code": "2205", "description": "CFC Longganisa Sausage - WIP", "raw_material": "Pork Back Fat", "kg_per_batch": 40, "percentage": 37.45},
            {"recipe_code": "2205", "description": "CFC Longganisa Sausage - WIP", "raw_material": "Filipino Longanisa Premix", "kg_per_batch": 16.5, "percentage": 15.45},
            {"recipe_code": "2205", "description": "CFC Longganisa Sausage - WIP", "raw_material": "Citrat", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 45, "percentage": 41.43},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 25, "percentage": 23.01},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Ice", "kg_per_batch": 20, "percentage": 18.41},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 10, "percentage": 9.21},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Salt", "kg_per_batch": 1.8, "percentage": 1.66},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.28},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.5, "percentage": 0.46},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.4, "percentage": 0.37},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Nutmeg Ground", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Paprika ", "kg_per_batch": 0.5, "percentage": 0.46},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Zitromat (Raps)", "kg_per_batch": 0.2, "percentage": 0.18},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Paprika Aqua Spice stable 15kg", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Preservative", "kg_per_batch": 0.08, "percentage": 0.07},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "ISP", "kg_per_batch": 1.5, "percentage": 1.38},
            {"recipe_code": "2023", "description": "Italian Sausage - WIP", "raw_material": "Rice Flour", "kg_per_batch": 3, "percentage": 2.76},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Beef 80CL", "kg_per_batch": 20.000, "percentage": 18.18},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 30.000, "percentage": 27.27},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Ice", "kg_per_batch": 20.000, "percentage": 18.18},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 30.000, "percentage": 27.27},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Salt", "kg_per_batch": 1.200, "percentage": 1.09},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "STPP", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.800, "percentage": 0.73},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.300, "percentage": 0.27},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Nutmeg Ground", "kg_per_batch": 0.100, "percentage": 0.09},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.100, "percentage": 0.09},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "MSG", "kg_per_batch": 0.100, "percentage": 0.09},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Rice Flour", "kg_per_batch": 6, "percentage": 5.45},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "ISP", "kg_per_batch": 1, "percentage": 0.91},
            {"recipe_code": "2038", "description": "MM - Beef Sausage - WIP", "raw_material": "Preservative Dry Sodium Sulphite 25kg", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 10, "percentage": 9.00},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 15, "percentage": 13.49},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Water", "kg_per_batch": 15, "percentage": 13.49},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 45, "percentage": 40.48},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Onions fresh", "kg_per_batch": 1, "percentage": 0.90},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 15, "percentage": 13.49},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Salt", "kg_per_batch": 1.2, "percentage": 1.08},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.27},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Pepper Black Ground", "kg_per_batch": 0.3, "percentage": 0.27},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Nutmeg Ground", "kg_per_batch": 0.06, "percentage": 0.05},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Zitromat (Raps)", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "MSG", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "dried parsely", "kg_per_batch": 0.2, "percentage": 0.18},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.8, "percentage": 0.72},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Preservative", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "Rice Flour", "kg_per_batch": 6, "percentage": 5.40},
            {"recipe_code": "2039", "description": "MM - Pork Sausage - WIP", "raw_material": "ISP", "kg_per_batch": 1, "percentage": 0.90},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Beef 80CL", "kg_per_batch": 50, "percentage": 45.70},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Chicken Skin", "kg_per_batch": 15, "percentage": 13.71},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 20, "percentage": 18.28},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Water", "kg_per_batch": 15, "percentage": 13.71},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Salt", "kg_per_batch": 1.35, "percentage": 1.23},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Sodium Erythorbate", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "GF Barbecue ASADA RUB", "kg_per_batch": 2, "percentage": 1.83},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.1, "percentage": 0.09},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "STPP", "kg_per_batch": 0.5, "percentage": 0.46},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "ISP", "kg_per_batch": 2, "percentage": 1.83},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Potato Starch", "kg_per_batch": 3, "percentage": 2.74},
            {"recipe_code": "2204", "description": "CFC Carne Asada Beef Sausage - WIP", "raw_material": "Sodium Bicarbonate", "kg_per_batch": 0.2, "percentage": 0.18},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 50, "percentage": 44.79},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Pork Jowls", "kg_per_batch": 40, "percentage": 35.84},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Pork Back Fat", "kg_per_batch": 0, "percentage": 0.00},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Water Iced (below 1⁰C)", "kg_per_batch": 10, "percentage": 8.96},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Dextrose Monohydrate", "kg_per_batch": 2, "percentage": 1.79},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Salt", "kg_per_batch": 1.8, "percentage": 1.61},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Mustard Powder", "kg_per_batch": 2.2, "percentage": 1.97},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.06, "percentage": 0.05},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 1.2, "percentage": 1.08},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "FUMARO", "kg_per_batch": 0.3, "percentage": 0.27},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Pepper White Ground", "kg_per_batch": 0.2, "percentage": 0.18},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "STPP", "kg_per_batch": 0.2, "percentage": 0.18},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Fermented Rice", "kg_per_batch": 0.01, "percentage": 0.01},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.15},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.13},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Paprika 3000 (Raps)", "kg_per_batch": 0.3, "percentage": 0.27},
            {"recipe_code": "2045", "description": "Tailgate Pork Franks - WIP", "raw_material": "Scansmoke PB-1200 25kg", "kg_per_batch": 0.8, "percentage": 0.72},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Pork Neck BL/RL", "kg_per_batch": 100, "percentage": 49.50},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Charsu Rap", "kg_per_batch": 2, "percentage": 0.99},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Water", "kg_per_batch": 75.04, "percentage": 37.14},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Salt", "kg_per_batch": 5.68, "percentage": 2.81},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Schiadit", "kg_per_batch": 2.08, "percentage": 1.03},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Sodium Bicarbonate", "kg_per_batch": 0.56, "percentage": 0.28},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Schinko", "kg_per_batch": 5.556, "percentage": 2.75},
            {"recipe_code": "1010", "description": "Charsu Pork Neck - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 11.12, "percentage": 5.50},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Pork 75 CL", "kg_per_batch": 39.35, "percentage": 36.52},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Water", "kg_per_batch": 17, "percentage": 15.78},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Emulsion Trim", "kg_per_batch": 20, "percentage": 18.56},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Diaphgram", "kg_per_batch": 13, "percentage": 12.07},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Chicken MDM", "kg_per_batch": 10.7, "percentage": 9.93},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Salt", "kg_per_batch": 1.667, "percentage": 1.55},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.14},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Schiadit", "kg_per_batch": 0.4, "percentage": 0.37},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.07, "percentage": 0.06},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Sugar Raw", "kg_per_batch": 0.8, "percentage": 0.74},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Potato Starch", "kg_per_batch": 2, "percentage": 1.86},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "STPP", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "1004", "description": "HF diced Bacon Logs - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.4, "percentage": 2.23},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Pork Topside", "kg_per_batch": 44, "percentage": 44.25},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Chicken MDM", "kg_per_batch": 10.7, "percentage": 10.76},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Water Iced (below 1⁰C)", "kg_per_batch": 22.74, "percentage": 22.87},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Pork Shoulder", "kg_per_batch": 12, "percentage": 12.07},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Salt", "kg_per_batch": 1.236, "percentage": 1.24},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.15},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Schiadit", "kg_per_batch": 0.5, "percentage": 0.50},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Schinko", "kg_per_batch": 1.09, "percentage": 1.10},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "MSG", "kg_per_batch": 0.197, "percentage": 0.20},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Frischex", "kg_per_batch": 0.494, "percentage": 0.50},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Potato Starch", "kg_per_batch": 1.978, "percentage": 1.99},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "ISP", "kg_per_batch": 0.989, "percentage": 0.99},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Colflo", "kg_per_batch": 0.989, "percentage": 0.99},
            {"recipe_code": "1024.4000.1", "description": "4x4 HAM", "raw_material": "Sodium Lactate", "kg_per_batch": 2.373, "percentage": 2.39},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Pork Topside", "kg_per_batch": 54.7, "percentage": 55.01},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Water Iced (below 1⁰C)", "kg_per_batch": 22.74, "percentage": 22.87},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Pork Shoulder", "kg_per_batch": 12, "percentage": 12.07},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Salt", "kg_per_batch": 1.236, "percentage": 1.24},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.15, "percentage": 0.15},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Schiadit", "kg_per_batch": 0.5, "percentage": 0.50},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Schinko", "kg_per_batch": 1.09, "percentage": 1.10},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "MSG", "kg_per_batch": 0.197, "percentage": 0.20},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Frischex", "kg_per_batch": 0.494, "percentage": 0.50},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Potato Starch", "kg_per_batch": 1.978, "percentage": 1.99},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "ISP", "kg_per_batch": 0.989, "percentage": 0.99},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Colflo", "kg_per_batch": 0.989, "percentage": 0.99},
            {"recipe_code": "1024", "description": "Costco Ham WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 2.373, "percentage": 2.39},
            {"recipe_code": "10003", "description": "Pulled Beef - WIP", "raw_material": "Beef 90CL", "kg_per_batch": 100, "percentage": 97.37},
            {"recipe_code": "10003", "description": "Pulled Beef - WIP", "raw_material": "Chorizo Spice (RAPS)", "kg_per_batch": 1.3, "percentage": 1.27},
            {"recipe_code": "10003", "description": "Pulled Beef - WIP", "raw_material": "Salt", "kg_per_batch": 1, "percentage": 0.97},
            {"recipe_code": "10003", "description": "Pulled Beef - WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "10003", "description": "Pulled Beef - WIP", "raw_material": "Chilli Flakes Dry", "kg_per_batch": 0.2, "percentage": 0.19},
            {"recipe_code": "1007GB", "description": "Pulled Pork GB WIP", "raw_material": "Pork Shoulder", "kg_per_batch": 100, "percentage": 50.00},
            {"recipe_code": "1007GB", "description": "Pulled Pork GB WIP", "raw_material": "Water", "kg_per_batch": 88.25, "percentage": 44.13},
            {"recipe_code": "1007GB", "description": "Pulled Pork GB WIP", "raw_material": "Salt", "kg_per_batch": 9, "percentage": 4.50},
            {"recipe_code": "1007GB", "description": "Pulled Pork GB WIP", "raw_material": "Schiadit", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1007GB", "description": "Pulled Pork GB WIP", "raw_material": "MSG", "kg_per_batch": 0.25, "percentage": 0.13},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Pork Hock", "kg_per_batch": 200, "percentage": 66.67},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Water", "kg_per_batch": 80, "percentage": 26.67},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Ice", "kg_per_batch": 12.32, "percentage": 4.11},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Salt", "kg_per_batch": 6, "percentage": 2.00},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.3, "percentage": 0.10},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.6, "percentage": 0.20},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "STPP", "kg_per_batch": 0.3, "percentage": 0.10},
            {"recipe_code": "9004", "description": "Hocks WIP", "raw_material": "Sodium Bicarbonate", "kg_per_batch": 0.48, "percentage": 0.16},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Pork 2 Piece Leg", "kg_per_batch": 100, "percentage": 50.00},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Water", "kg_per_batch": 58.4, "percentage": 29.20},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Ice", "kg_per_batch": 15, "percentage": 7.50},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Salt", "kg_per_batch": 8, "percentage": 4.00},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.75, "percentage": 0.38},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Schiadit", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.75, "percentage": 0.38},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Colorado CM", "kg_per_batch": 0.1, "percentage": 0.05},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Frischex", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1003", "description": "Ham - WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 12, "percentage": 6.00},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Pork Topside", "kg_per_batch": 100, "percentage": 50.00},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Water", "kg_per_batch": 58.4, "percentage": 29.20},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Ice", "kg_per_batch": 15, "percentage": 7.50},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Salt", "kg_per_batch": 8, "percentage": 4.00},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.75, "percentage": 0.38},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Schiadit", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.75, "percentage": 0.38},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Colorado CM", "kg_per_batch": 0.1, "percentage": 0.05},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Frischex", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1003.8", "description": "Ham Slicing Log - Whole", "raw_material": "Sodium Lactate", "kg_per_batch": 12, "percentage": 6.00},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Pork Loin RL pan size square cut 200mm width total", "kg_per_batch": 100, "percentage": 49.92},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Pepper Extract", "kg_per_batch": 0.25, "percentage": 0.12},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Garlic Powder", "kg_per_batch": 0.064, "percentage": 0.03},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Water", "kg_per_batch": 58.4, "percentage": 29.15},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Ice", "kg_per_batch": 15, "percentage": 7.49},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Salt", "kg_per_batch": 8, "percentage": 3.99},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Ultra Cure/hi cure", "kg_per_batch": 0.75, "percentage": 0.37},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Schiadit", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Gluta Clean (Raps)", "kg_per_batch": 0.75, "percentage": 0.37},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Colorado CM", "kg_per_batch": 0.1, "percentage": 0.05},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Frischex", "kg_per_batch": 2.5, "percentage": 1.25},
            {"recipe_code": "1005", "description": "Pan Size WIP", "raw_material": "Sodium Lactate", "kg_per_batch": 12, "percentage": 5.99}
        ]

        print("Inserting Recipe Details into RecipeMaster...")
        for recipe_line in recipe_details:
            recipe_code = recipe_line['recipe_code']
            raw_material_name = recipe_line['raw_material']
            kg_per_batch = recipe_line['kg_per_batch']
            percentage = recipe_line['percentage']
            description = recipe_line['description']

            # Find the raw_material_id from ItemMaster
            raw_material_item = ItemMaster.query.filter_by(
                description=raw_material_name,
                item_type='raw_material'
            ).first()

            # Find the finished_good_id from ItemMaster
            finished_good_item = ItemMaster.query.filter_by(
                item_code=recipe_code,
                item_type='finished_good'
            ).first()

            if raw_material_item and finished_good_item:
                # Check if this specific recipe entry already exists to prevent duplicates
                existing_recipe_entry = RecipeMaster.query.filter_by(
                    recipe_code=recipe_code,
                    raw_material_id=raw_material_item.id,
                    finished_good_id=finished_good_item.id
                ).first()

                if not existing_recipe_entry:
                    recipe_entry = RecipeMaster(
                        recipe_code=recipe_code,
                        description=description,
                        raw_material_id=raw_material_item.id,
                        finished_good_id=finished_good_item.id,
                        kg_per_batch=kg_per_batch,
                        percentage=percentage
                    )
                    db.session.add(recipe_entry)
                else:
                    print(f"Skipping existing recipe entry: Recipe Code '{recipe_code}', Raw Material '{raw_material_name}'")
            else:
                print(f"Warning: Could not find ItemMaster entry for Raw Material '{raw_material_name}' (Type: raw_material) or Finished Good '{recipe_code}' (Type: finished_good). Skipping recipe entry.")

        db.session.commit()
        print("\nRecipeMaster data inserted successfully!")

    except ValueError as e:
        db.session.rollback()
        print(f"Data insertion failed due to validation error: {e}")
    except Exception as e:
        db.session.rollback()
        print(f"An unexpected error occurred during data insertion: {e}")
    finally:
        db.session.close()

# How to run this script:
# This function needs to be executed within your Flask application context
# if your `db` object is tied to it.
# Example:
# from your_app import app # assuming 'app' is your Flask application instance
# with app.app_context():
#     insert_recipe_master_data()

# If running standalone, ensure your db and models are initialized correctly:
# from your_project.database import db
# from your_project.models.item_master import ItemMaster
# from your_project.models.recipe_master import RecipeMaster
# # Add code here to set up your database connection if not using Flask app_context
# # For example:
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://root:german@localhost/gbdb'
db.init_app(app)
with app.app_context():
    insert_recipe_master_data()