"""Initial migration after complete and total reset

Revision ID: 3ab19a553d04
Revises: 
Create Date: 2025-07-10 14:51:16.369440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ab19a553d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_master_backup_flexible_schema')
    op.drop_table('item_master_backup')
    op.drop_table('recipe_master_backup_old_structure')
    op.drop_table('recipe_master_backup')
    op.drop_table('item_master_backup_flexible_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_master_backup_flexible_schema',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('item_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machinery_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_level', mysql.FLOAT(), nullable=True),
    sa.Column('max_level', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('price_per_kg', mysql.FLOAT(), nullable=True),
    sa.Column('is_make_to_order', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('kg_per_unit', mysql.FLOAT(), nullable=True),
    sa.Column('units_per_bag', mysql.FLOAT(), nullable=True),
    sa.Column('loss_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('fw', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('calculation_factor', mysql.FLOAT(), nullable=True),
    sa.Column('price_per_uom', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Price per unit of measure'),
    sa.Column('avg_weight_per_unit', mysql.FLOAT(), nullable=True, comment='Average weight per unit in kg'),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True, comment='Name of the supplier for this item'),
    sa.Column('item_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('wip_item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wipf_item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe_master_backup',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('recipe_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('raw_material_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kg_per_batch', mysql.FLOAT(), nullable=True),
    sa.Column('percentage', mysql.FLOAT(), nullable=True),
    sa.Column('week_commencing', sa.DATE(), nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe_master_backup_old_structure',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('recipe_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('raw_material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finished_good_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kg_per_batch', mysql.FLOAT(), nullable=True),
    sa.Column('percentage', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('item_master_backup',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('item_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machinery_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_level', mysql.FLOAT(), nullable=True),
    sa.Column('max_level', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('price_per_kg', mysql.FLOAT(), nullable=True),
    sa.Column('is_make_to_order', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('kg_per_unit', mysql.FLOAT(), nullable=True),
    sa.Column('units_per_bag', mysql.FLOAT(), nullable=True),
    sa.Column('loss_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('fw', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('calculation_factor', mysql.FLOAT(), nullable=True),
    sa.Column('price_per_uom', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Price per unit of measure'),
    sa.Column('avg_weight_per_unit', mysql.FLOAT(), nullable=True, comment='Average weight per unit in kg'),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True, comment='Name of the supplier for this item'),
    sa.Column('item_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe_master_backup_flexible_schema',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('recipe_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('finished_good_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_material_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kg_per_batch', mysql.FLOAT(), nullable=True),
    sa.Column('quantity_uom_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percentage', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
